---- DDL DATABASE DEFINITION LANGUAGE

-- CRIAR BANCO DE DADOS
CREATE DATABASE [Event+_Manha]

USE [Event+_Manha]

--  CRIAR TABELAS

CREATE TABLE TipoUsuario
(
	IdTipoUsuario INT PRIMARY KEY IDENTITY,
	Titulo VARCHAR(20) NOT NULL UNIQUE
)

CREATE TABLE TipoEvento
(
	IdTipoEvento INT PRIMARY KEY IDENTITY,
	Titulo VARCHAR(220) NOT NULL UNIQUE
)

CREATE TABLE Instituicao
(
	IdInstituicao INT PRIMARY KEY IDENTITY,
	CNPJ CHAR(14) NOT NULL UNIQUE,
	NomeFantasia VARCHAR (30) NOT NULL,
	Endereco VARCHAR(30) NOT NULL
)

CREATE TABLE Usuario
(
	IdUsuario INT PRIMARY KEY IDENTITY,
	IdTipoUsuario INT FOREIGN KEY REFERENCES TipoUsuario(IdTipoUsuario) NOT NULL,
	Nome VARCHAR(20) NOT NULL,
	Email VARCHAR(20) NOT NULL UNIQUE,
	Senha VARCHAR(20) NOT NULL
)

CREATE TABLE Evento
(
	IdEvento INT PRIMARY KEY IDENTITY,
	IdTipoEvento INT FOREIGN KEY REFERENCES TipoEvento(IdTipoEvento) NOT NULL,
	IdInstituicao INT FOREIGN KEY REFERENCES Instituicao(IdInstituicao) NOT NULL,
	Nome VARCHAR(50) NOT NULL,
	Descricao VARCHAR(256) NOT NULL,
	[Data] DATE NOT NULL,
	Horario TIME NOT NULL
)

CREATE TABLE PresencaEvento
(
	IdPresencaEvento INT PRIMARY KEY IDENTITY,
	IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario) NOT NULL,
	IdEvento INT FOREIGN KEY REFERENCES Evento(IdEvento) NOT NULL,
	Situacao BIT DEFAULT (0)
)

CREATE TABLE Comentario
(
	IdComentario INT PRIMARY KEY IDENTITY,
	IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario) NOT NULL,
	IdEvento INT FOREIGN KEY REFERENCES Evento(IdEvento) NOT NULL,
	Descricao VARCHAR(256) NOT NULL,
	Exibir BIT DEFAULT 0
)

